services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=/api/upload
      - VITE_API_PROXY_TARGET=http://backend:8000
      - VITE_API_KEY=dev_secret_123
    depends_on:
      - backend
  backend:
    build: ./src/backend
    ports:
      - 8000:8000
    volumes:
      - ./src/backend:/app
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - API_SECRET_KEY=dev_secret_123
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:v3.10.0
    ports: 
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
  
  grafana:
    image: grafana/grafana:12.3.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./infra/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/monitoring/grafana:/etc/grafana/custom-dashboards
    depends_on:
      - prometheus

volumes:
  grafana-storage: