services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=/api/upload
      - VITE_API_PROXY_TARGET=http://backend:8000
    depends_on:
      - backend
  backend:
    build: ./src/backend
    ports:
      - 8000:8000
    volumes:
      - ./src/backend:/app
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:v3.10.0
    ports: 
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
  
  grafana:
    image: grafana/grafana:12.3.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage: