{
 "title": "App Health",
 "description": "Tracks the RED Metrics (Rate, Errors, Duration) to monitor exactly what the end-user is experiencing when interacting with the API.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Tracks the volume of bad uploads (400s) and server crashes (500s).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{job=\"boxdmetrics-api\", handler=\"/api/upload\", status=~\"4xx|5xx\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "description": "Tracks the rate of users hitting the upload endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/api/upload\", job=\"boxdmetrics-api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Processing Time",
   "type": "timeseries",
   "description": "Calculates the true average duration of a CSV upload by dividing total time spent by total requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"boxdmetrics-api\", handler=\"/api/upload\"}[5m]) / rate(http_request_duration_seconds_count{job=\"boxdmetrics-api\", handler=\"/api/upload\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Latency (P95)",
   "type": "timeseries",
   "description": "Ensures that 95% of users are experiencing fast processing times.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{handler=\"/api/upload\", job=\"boxdmetrics-api\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}