{
 "title": "Infrastructure",
 "description": " Tracks the USE Metrics (Utilization, Saturation, Errors) for the backend Docker container. Used for debugging performance bottlenecks.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Tracks the percentage of CPU utilized by the FastAPI process.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"boxdmetrics-api\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "description": "Counts how many times the Python application process had to restart in the last 24 hours.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Short / None" } },
   "targets": [
    {
     "expr": "changes(process_start_time_seconds{job=\"boxdmetrics-api\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (RAM)",
   "type": "timeseries",
   "description": "Monitors the rate of change in memory to detect Pandas memory leaks or heavy CSV loads.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "deriv(process_resident_memory_bytes{job=\"boxdmetrics-api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}